# Generated by Django 4.2.7 on 2025-02-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensordata'),
    ]

    operations = [
    ]
